[package]
name = "oxide-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
oxide-core.workspace = true
oxide-datapack.workspace = true
oxide-noise.workspace = true
oxide-biome.workspace = true
oxide-chunkgen.workspace = true
anyhow.workspace = true
