package dev.oxide.plugin;

import dev.oxide.plugin.ffi.OxideNative;
import dev.oxide.plugin.generator.GeneratorService;
import dev.oxide.plugin.generator.OxideChunkGenerator;
import dev.oxide.plugin.provenance.LiveProvenance;
import dev.oxide.plugin.provenance.ProvenanceLookup;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;
import org.bukkit.Bukkit;
import org.bukkit.WorldCreator;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.command.TabCompleter;
import org.bukkit.entity.Player;
import org.bukkit.plugin.Plugin;

import java.util.List;

/**
 * {@code /oxide debug on|off}      — toggles the per-player action-bar overlay.
 * {@code /oxide here}              — one-shot detail dump for the sender's current chunk.
 * {@code /oxide createworld <name> [seed]} — creates a new world generated by
 *                                     {@link OxideChunkGenerator} (wave 5). See its class doc
 *                                     and {@code oxide-ffi}'s module doc for what it does and
 *                                     doesn't produce yet.
 *
 * Threading: Folia does not guarantee a player-issued command is processed
 * on the region thread that currently owns that player — command dispatch
 * runs on whatever thread received the packet, which need not line up with
 * the sender entity's owning region. Every branch that reads the Player's
 * location or sends it a message is therefore wrapped in
 * {@code player.getScheduler().run(...)} (the per-entity scheduler) so it
 * always executes on the thread that currently owns that player.
 * {@code Bukkit.getScheduler()} is never used here — see ChunkTracker for
 * the fuller rationale, which applies identically to this class.
 *
 * {@code createworld} is different: creating a world isn't bound to any
 * entity or existing region, so it runs on
 * {@code Bukkit.getGlobalRegionScheduler()} instead of a per-entity one.
 */
public final class OxideCommand implements CommandExecutor, TabCompleter {

    private final Plugin plugin;
    private final DebugState debugState;
    private final ProvenanceLookup provenanceLookup;
    private final LiveProvenance liveProvenance;
    private final GeneratorService generatorService;

    public OxideCommand(Plugin plugin, DebugState debugState, ProvenanceLookup provenanceLookup,
                         LiveProvenance liveProvenance, GeneratorService generatorService) {
        this.plugin = plugin;
        this.debugState = debugState;
        this.provenanceLookup = provenanceLookup;
        this.liveProvenance = liveProvenance;
        this.generatorService = generatorService;
    }

    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        // createworld doesn't need a Player (console/RCON should be able to provision a test
        // world too) and has its own permission, so it's handled before the player-only gate
        // below applies to every other subcommand.
        if (args.length >= 1 && args[0].equalsIgnoreCase("createworld")) {
            if (!sender.hasPermission("oxide.createworld")) {
                sender.sendMessage(Component.text("You do not have permission to use this command.", NamedTextColor.RED));
                return true;
            }
            if (args.length < 2) {
                sender.sendMessage(Component.text("Usage: /oxide createworld <name> [seed]", NamedTextColor.RED));
                return true;
            }
            createWorld(sender, args[1], args.length >= 3 ? args[2] : null);
            return true;
        }

        if (!(sender instanceof Player player)) {
            sender.sendMessage(Component.text("This command can only be used by a player.", NamedTextColor.RED));
            return true;
        }
        if (!player.hasPermission("oxide.debug")) {
            player.sendMessage(Component.text("You do not have permission to use this command.", NamedTextColor.RED));
            return true;
        }

        if (args.length == 2 && args[0].equalsIgnoreCase("debug")) {
            boolean on = args[1].equalsIgnoreCase("on");
            boolean off = args[1].equalsIgnoreCase("off");
            if (!on && !off) {
                player.sendMessage(Component.text("Usage: /oxide debug <on|off>", NamedTextColor.RED));
                return true;
            }
            // Toggling shared state doesn't touch the Player entity itself,
            // safe to do directly on whatever thread dispatched the command.
            debugState.setEnabled(player.getUniqueId(), on);
            player.getScheduler().run(plugin,
                    task -> player.sendMessage(Component.text(
                            "chunkgen debug overlay: " + (on ? "on" : "off"), NamedTextColor.GRAY)),
                    null);
            return true;
        }

        if (args.length == 1 && args[0].equalsIgnoreCase("here")) {
            player.getScheduler().run(plugin, task -> printHere(player), null);
            return true;
        }

        player.sendMessage(Component.text("Usage: /oxide debug <on|off> | /oxide here", NamedTextColor.RED));
        return true;
    }

    /** Runs on the player's owning entity scheduler — see class javadoc. */
    private void printHere(Player player) {
        int chunkX = player.getLocation().getBlockX() >> 4;
        int chunkZ = player.getLocation().getBlockZ() >> 4;
        ProvenanceLookup.Result result = provenanceLookup.lookup(
                player.getWorld().getName(), player.getWorld().getWorldFolder(), chunkX, chunkZ);

        // The live answer first: what generated this chunk on this server. Everything below it
        // is the offline sidecar view, which only says something for a world produced by
        // oxide-pregen -- on a live server it is always absent, which is not evidence of
        // anything and is labelled so it cannot be read as "this chunk is vanilla".
        player.sendMessage(Component.text("chunk: " + chunkX + ", " + chunkZ, NamedTextColor.GRAY));
        player.sendMessage(Component.text("generated by: ", NamedTextColor.GRAY)
                .append(ActionBarPresenter.render(liveProvenance.of(player.getChunk()))));

        player.sendMessage(Component.text("--- offline sidecar (oxide-pregen only) ---", NamedTextColor.DARK_GRAY));
        player.sendMessage(Component.text("region file: " + result.regionFile().getFileName(), NamedTextColor.DARK_GRAY));
        String sidecarLine = "sidecar present: " + result.sidecarPresent()
                + (result.sidecarParseError() ? " (parse error, see server log)" : "")
                + (result.sidecarPresent() ? "" : " (normal on a live server)");
        player.sendMessage(Component.text(sidecarLine, NamedTextColor.DARK_GRAY));
    }

    /**
     * Runs on the global region scheduler — see class javadoc. Opening the native handle
     * (loading the library, parsing the datapack, building the noise router) and creating the
     * world both happen here, synchronously, on that one global-scheduler tick: acceptable for
     * a manual test command, not something to do on every server start.
     */
    private void createWorld(CommandSender sender, String name, String seedArg) {
        if (Bukkit.getWorld(name) != null) {
            sender.sendMessage(Component.text("A world named '" + name + "' already exists.", NamedTextColor.RED));
            return;
        }
        long seed = seedArg != null ? parseSeed(seedArg) : System.nanoTime();

        Bukkit.getGlobalRegionScheduler().run(plugin, task -> {
            sender.sendMessage(Component.text(
                    "Opening oxide generator (loading datapack, building noise router)...", NamedTextColor.GRAY));
            final OxideNative.Handle handle;
            try {
                handle = generatorService.openHandle(seed);
            } catch (RuntimeException e) {
                sender.sendMessage(Component.text("Failed to open oxide generator: " + e.getMessage(), NamedTextColor.RED));
                return;
            }
            sender.sendMessage(Component.text(
                    "Generator ready (default block: " + handle.defaultBlockName()
                            + ", default fluid: " + handle.defaultFluidName()
                            + ", min_y/height: " + handle.minY() + "/" + handle.height()
                            + "). Creating world '" + name + "' seed=" + seed + "...", NamedTextColor.GRAY));
            try {
                new WorldCreator(name)
                        .generator(new OxideChunkGenerator(
                                generatorService, liveProvenance, plugin.getLogger(), seed))
                        .createWorld();
                sender.sendMessage(Component.text("World '" + name + "' created.", NamedTextColor.GREEN));
            } catch (RuntimeException e) {
                sender.sendMessage(Component.text("World creation failed: " + e.getMessage(), NamedTextColor.RED));
            }
        });
    }

    private static long parseSeed(String raw) {
        try {
            return Long.parseLong(raw);
        } catch (NumberFormatException e) {
            return raw.hashCode(); // matches vanilla's own "arbitrary string as seed" behavior
        }
    }

    @Override
    public List<String> onTabComplete(CommandSender sender, Command command, String alias, String[] args) {
        if (args.length == 1) {
            return List.of("debug", "here", "createworld");
        }
        if (args.length == 2 && args[0].equalsIgnoreCase("debug")) {
            return List.of("on", "off");
        }
        return List.of();
    }
}
