package dev.oxide.plugin;

import dev.oxide.plugin.provenance.ProvenanceLookup;
import dev.oxide.plugin.provenance.SidecarCache;
import org.bukkit.command.PluginCommand;
import org.bukkit.plugin.java.JavaPlugin;

/**
 * Oxide chunk-provenance debug plugin.
 *
 * DEBUG-ONLY diagnostic: shows, via the action bar, whether the chunk a
 * player is standing in was generated by Oxide (Rust) or vanilla Java. This
 * is read-only and display-only — it is not the milestone-5 hot-radius
 * router; it implements no chunk routing, no player-radius pregen
 * scheduling, and no generation logic of any kind. See plugin/README.md.
 */
public final class OxidePlugin extends JavaPlugin {

    private DebugState debugState;

    @Override
    public void onEnable() {
        debugState = new DebugState();
        SidecarCache sidecarCache = new SidecarCache(getLogger());
        ProvenanceLookup provenanceLookup = new ProvenanceLookup(sidecarCache);

        getServer().getPluginManager().registerEvents(
                new ChunkTracker(this, debugState, provenanceLookup), this);

        OxideCommand command = new OxideCommand(this, debugState, provenanceLookup);
        PluginCommand pluginCommand = getCommand("oxide");
        if (pluginCommand != null) {
            pluginCommand.setExecutor(command);
            pluginCommand.setTabCompleter(command);
        } else {
            getLogger().severe("`oxide` command not registered -- check paper-plugin.yml");
        }
    }

    @Override
    public void onDisable() {
        // Nothing to release: SidecarCache holds only in-memory parsed
        // bitmaps (no open file handles kept between lookups), and this
        // plugin schedules no repeating tasks to cancel.
    }
}
