package dev.oxide.plugin;

import dev.oxide.plugin.ffi.OxideNative;
import dev.oxide.plugin.generator.GeneratorService;
import dev.oxide.plugin.generator.OxideChunkGenerator;
import dev.oxide.plugin.provenance.LiveProvenance;
import dev.oxide.plugin.provenance.ProvenanceLookup;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;
import org.bukkit.Bukkit;
import org.bukkit.WorldCreator;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.command.TabCompleter;
import org.bukkit.entity.Player;
import org.bukkit.plugin.Plugin;

import java.util.List;

/**
 * {@code /oxide debug on|off}      — toggles the per-player action-bar overlay.
 * {@code /oxide here}              — one-shot detail dump for the sender's current chunk.
 * {@code /oxide createworld <name> [seed]} — creates a new world generated by
 *                                     {@link OxideChunkGenerator} (wave 5). See its class doc
 *                                     and {@code oxide-ffi}'s module doc for what it does and
 *                                     doesn't produce yet.
 *
 * Threading: Folia does not guarantee a player-issued command is processed
 * on the region thread that currently owns that player — command dispatch
 * runs on whatever thread received the packet, which need not line up with
 * the sender entity's owning region. Every branch that reads the Player's
 * location or sends it a message is therefore wrapped in
 * {@code player.getScheduler().run(...)} (the per-entity scheduler) so it
 * always executes on the thread that currently owns that player.
 * {@code Bukkit.getScheduler()} is never used here — see ChunkTracker for
 * the fuller rationale, which applies identically to this class.
 *
 * {@code createworld} is different: creating a world isn't bound to any
 * entity or existing region, so it runs on
 * {@code Bukkit.getGlobalRegionScheduler()} instead of a per-entity one.
 */
public final class OxideCommand implements CommandExecutor, TabCompleter {

    private final Plugin plugin;
    private final DebugState debugState;
    private final ProvenanceLookup provenanceLookup;
    private final LiveProvenance liveProvenance;
    private final GeneratorService generatorService;
    private final dev.oxide.plugin.pacside.PacsideManager pacsideManager;

    public OxideCommand(Plugin plugin, DebugState debugState, ProvenanceLookup provenanceLookup,
                         LiveProvenance liveProvenance, GeneratorService generatorService,
                         dev.oxide.plugin.pacside.PacsideManager pacsideManager) {
        this.plugin = plugin;
        this.debugState = debugState;
        this.provenanceLookup = provenanceLookup;
        this.liveProvenance = liveProvenance;
        this.generatorService = generatorService;
        this.pacsideManager = pacsideManager;
    }

    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        // createworld doesn't need a Player (console/RCON should be able to provision a test
        // world too) and has its own permission, so it's handled before the player-only gate
        // below applies to every other subcommand.
        if (args.length >= 1 && args[0].equalsIgnoreCase("createworld")) {
            if (!sender.hasPermission("oxide.createworld")) {
                sender.sendMessage(Component.text("You do not have permission to use this command.", NamedTextColor.RED));
                return true;
            }
            if (args.length < 2) {
                sender.sendMessage(Component.text("Usage: /oxide createworld <name> [seed]", NamedTextColor.RED));
                return true;
            }
            createWorld(sender, args[1], args.length >= 3 ? args[2] : null);
            return true;
        }

        if (args.length >= 1 && args[0].equalsIgnoreCase("stress")) {
            if (!sender.hasPermission("oxide.debug")) {
                sender.sendMessage(Component.text("You do not have permission to use this command.", NamedTextColor.RED));
                return true;
            }
            if (args.length >= 2 && args[1].equalsIgnoreCase("stop")) {
                pacsideManager.getStressSimulator().stop();
                return true;
            }
            if (args.length >= 2 && args[1].equalsIgnoreCase("fly")) {
                int flyers = 16;
                double speed = 35.0;
                int duration = 60;
                try {
                    if (args.length >= 3) flyers = Integer.parseInt(args[2]);
                    if (args.length >= 4) speed = Double.parseDouble(args[3]);
                    if (args.length >= 5) duration = Integer.parseInt(args[4]);
                } catch (NumberFormatException e) {
                    sender.sendMessage(Component.text("Invalid numbers. Usage: /oxide stress fly [flyers=16] [speed=35] [duration=60]", NamedTextColor.RED));
                    return true;
                }

                org.bukkit.Location loc = (sender instanceof Player p) ? p.getLocation() :
                        sender.getServer().getWorlds().get(0).getSpawnLocation();
                pacsideManager.getStressSimulator().start(loc.getWorld(), loc, flyers, speed, duration);
                return true;
            }
            sender.sendMessage(Component.text("Usage: /oxide stress fly [flyers] [speed_mps] [duration_sec] | /oxide stress stop", NamedTextColor.RED));
            return true;
        }

        if (args.length >= 1 && args[0].equalsIgnoreCase("pacside")) {
            if (!sender.hasPermission("oxide.debug")) {
                sender.sendMessage(Component.text("You do not have permission to use this command.", NamedTextColor.RED));
                return true;
            }
            if (args.length == 1 || (args.length == 2 && args[1].equalsIgnoreCase("stats"))) {
                sender.sendMessage(Component.text("--- Pacside Chunk Streamer ---", NamedTextColor.GOLD));
                sender.sendMessage(Component.text("Prefetcher: ", NamedTextColor.GRAY)
                        .append(Component.text(pacsideManager.getPrefetcher().isEnabled() ? "ENABLED" : "DISABLED",
                                pacsideManager.getPrefetcher().isEnabled() ? NamedTextColor.GREEN : NamedTextColor.RED)));
                sender.sendMessage(Component.text("Prefetched Chunks: ", NamedTextColor.GRAY)
                        .append(Component.text(pacsideManager.getPrefetcher().getPrefetchedCount(), NamedTextColor.AQUA)));
                return true;
            }
            if (args.length >= 2 && args[1].equalsIgnoreCase("fetch")) {
                if (!(sender instanceof Player player)) {
                    sender.sendMessage(Component.text("The fetch command can only be used by a player in-game.", NamedTextColor.RED));
                    return true;
                }
                int radius = 1000;
                try {
                    if (args.length >= 4 && args[2].equalsIgnoreCase("radius")) {
                        radius = Integer.parseInt(args[3]);
                    } else if (args.length >= 3) {
                        radius = Integer.parseInt(args[2]);
                    }
                } catch (NumberFormatException e) {
                    player.sendMessage(Component.text("Invalid radius number: " + (args.length >= 4 ? args[3] : args[2]), NamedTextColor.RED));
                    return true;
                }
                pacsideManager.getPrefetcher().prefetchRadius(player, radius);
                return true;
            }
            if (args.length == 3 && args[1].equalsIgnoreCase("hud")) {
                if (!(sender instanceof Player player)) {
                    sender.sendMessage(Component.text("This command can only be used by a player.", NamedTextColor.RED));
                    return true;
                }
                boolean enable = args[2].equalsIgnoreCase("on");
                pacsideManager.getPrefetcher().toggleVisualHud(player.getUniqueId(), enable);
                player.sendMessage(Component.text("[Pacside] Visual HUD & Particle Indicator: " + (enable ? "ENABLED" : "DISABLED"),
                        enable ? NamedTextColor.GREEN : NamedTextColor.RED));
                return true;
            }
            if (args.length == 2 && args[1].equalsIgnoreCase("clear")) {
                dev.oxide.plugin.pacside.PacsideNative.clear();
                sender.sendMessage(Component.text("Pacside native off-heap cache cleared.", NamedTextColor.GREEN));
                return true;
            }
            if (args.length == 3 && args[1].equalsIgnoreCase("prefetch")) {
                boolean enable = args[2].equalsIgnoreCase("on");
                pacsideManager.getPrefetcher().setEnabled(enable);
                sender.sendMessage(Component.text("Pacside prefetcher: " + (enable ? "ENABLED" : "DISABLED"),
                        enable ? NamedTextColor.GREEN : NamedTextColor.RED));
                return true;
            }
            sender.sendMessage(Component.text("Usage: /oxide pacside [stats|fetch radius <blocks>|hud on/off|clear|prefetch on/off]", NamedTextColor.RED));
            return true;
        }

        if (!(sender instanceof Player player)) {
            sender.sendMessage(Component.text("This command can only be used by a player.", NamedTextColor.RED));
            return true;
        }
        if (!player.hasPermission("oxide.debug")) {
            player.sendMessage(Component.text("You do not have permission to use this command.", NamedTextColor.RED));
            return true;
        }

        if (args.length == 2 && args[0].equalsIgnoreCase("debug")) {
            boolean on = args[1].equalsIgnoreCase("on");
            boolean off = args[1].equalsIgnoreCase("off");
            if (!on && !off) {
                player.sendMessage(Component.text("Usage: /oxide debug <on|off>", NamedTextColor.RED));
                return true;
            }
            // Toggling shared state doesn't touch the Player entity itself,
            // safe to do directly on whatever thread dispatched the command.
            debugState.setEnabled(player.getUniqueId(), on);
            player.getScheduler().run(plugin,
                    task -> player.sendMessage(Component.text(
                            "chunkgen debug overlay: " + (on ? "on" : "off"), NamedTextColor.GRAY)),
                    null);
            return true;
        }

        if (args.length == 1 && args[0].equalsIgnoreCase("here")) {
            player.getScheduler().run(plugin, task -> printHere(player), null);
            return true;
        }

        player.sendMessage(Component.text("Usage: /oxide debug <on|off> | /oxide here | /oxide pacside", NamedTextColor.RED));
        return true;
    }

    /** Runs on the player's owning entity scheduler — see class javadoc. */
    private void printHere(Player player) {
        int chunkX = player.getLocation().getBlockX() >> 4;
        int chunkZ = player.getLocation().getBlockZ() >> 4;
        ProvenanceLookup.Result result = provenanceLookup.lookup(
                player.getWorld().getName(), player.getWorld().getWorldFolder(), chunkX, chunkZ);

        // The live answer first: what generated this chunk on this server. Everything below it
        // is the offline sidecar view, which only says something for a world produced by
        // oxide-pregen -- on a live server it is always absent, which is not evidence of
        // anything and is labelled so it cannot be read as "this chunk is vanilla".
        player.sendMessage(Component.text("chunk: " + chunkX + ", " + chunkZ, NamedTextColor.GRAY));
        player.sendMessage(Component.text("generated by: ", NamedTextColor.GRAY)
                .append(ActionBarPresenter.render(liveProvenance.of(player.getChunk()))));

        boolean isPacsideWarmed = pacsideManager.getPrefetcher().isChunkPrefetched(chunkX, chunkZ);
        player.sendMessage(Component.text("pacside cache: ", NamedTextColor.GRAY)
                .append(isPacsideWarmed ? Component.text("PRE-FETCHED (Native RAM Cache)", NamedTextColor.GREEN)
                        : Component.text("DISK LOADED", NamedTextColor.YELLOW)));

        player.sendMessage(Component.text("--- offline sidecar (oxide-pregen only) ---", NamedTextColor.DARK_GRAY));
        player.sendMessage(Component.text("region file: " + result.regionFile().getFileName(), NamedTextColor.DARK_GRAY));
        String sidecarLine = "sidecar present: " + result.sidecarPresent()
                + (result.sidecarParseError() ? " (parse error, see server log)" : "")
                + (result.sidecarPresent() ? "" : " (normal on a live server)");
        player.sendMessage(Component.text(sidecarLine, NamedTextColor.DARK_GRAY));
    }

    /**
     * Runs on the global region scheduler — see class javadoc. Opening the native handle
     * (loading the library, parsing the datapack, building the noise router) and creating the
     * world both happen here, synchronously, on that one global-scheduler tick: acceptable for
     * a manual test command, not something to do on every server start.
     */
    private void createWorld(CommandSender sender, String name, String seedArg) {
        if (Bukkit.getWorld(name) != null) {
            sender.sendMessage(Component.text("A world named '" + name + "' already exists.", NamedTextColor.RED));
            return;
        }
        long seed = seedArg != null ? parseSeed(seedArg) : System.nanoTime();

        Bukkit.getGlobalRegionScheduler().run(plugin, task -> {
            sender.sendMessage(Component.text(
                    "Opening oxide generator (loading datapack, building noise router)...", NamedTextColor.GRAY));
            final OxideNative.Handle handle;
            try {
                // createworld makes a NORMAL world, so overworld settings -- unless config
                // names a dimension explicitly.
                String dimensionId = generatorService.configuredDimensionId();
                handle = generatorService.openHandle(
                        seed, dimensionId == null || dimensionId.isBlank()
                                ? "minecraft:overworld" : dimensionId);
            } catch (RuntimeException e) {
                sender.sendMessage(Component.text("Failed to open oxide generator: " + e.getMessage(), NamedTextColor.RED));
                return;
            }
            sender.sendMessage(Component.text(
                    "Generator ready (default block: " + handle.defaultBlockName()
                            + ", default fluid: " + handle.defaultFluidName()
                            + ", min_y/height: " + handle.minY() + "/" + handle.height()
                            + "). Creating world '" + name + "' seed=" + seed + "...", NamedTextColor.GRAY));
            try {
                new WorldCreator(name)
                        .generator(new OxideChunkGenerator(
                                generatorService, liveProvenance, plugin.getLogger(), seed))
                        .createWorld();
                sender.sendMessage(Component.text("World '" + name + "' created.", NamedTextColor.GREEN));
            } catch (RuntimeException e) {
                sender.sendMessage(Component.text("World creation failed: " + e.getMessage(), NamedTextColor.RED));
            }
        });
    }

    private static long parseSeed(String raw) {
        try {
            return Long.parseLong(raw);
        } catch (NumberFormatException e) {
            return raw.hashCode(); // matches vanilla's own "arbitrary string as seed" behavior
        }
    }

    @Override
    public List<String> onTabComplete(CommandSender sender, Command command, String alias, String[] args) {
        if (args.length == 1) {
            return List.of("debug", "here", "createworld");
        }
        if (args.length == 2 && args[0].equalsIgnoreCase("debug")) {
            return List.of("on", "off");
        }
        return List.of();
    }
}
