//! Per-region provenance sidecar: which chunks in a `.mca` were generated by Oxide.
//!
//! **Why not a chunk NBT tag.** Minecraft re-serializes a loaded chunk from its in-memory object
//! graph and drops any NBT tag it doesn't recognize. A custom root key would survive exactly
//! until the chunk is next marked dirty and saved by the server, then silently vanish. So Oxide
//! tracks provenance out-of-band, in a sidecar file it owns end-to-end: `r.<x>.<z>.mca.oxide`,
//! sitting next to the region file it describes.
//!
//! # On-disk format (fixed — matches the parallel Java plugin byte for byte)
//!
//! 136 bytes, little-endian where multi-byte:
//!
//! | bytes    | field                                    |
//! |----------|-------------------------------------------|
//! | `0..4`   | magic ASCII `OXPV`                         |
//! | `4`      | `u8` format version, currently `1`         |
//! | `5`      | `u8` flags, currently `0`                  |
//! | `6..8`   | `u16` reserved, currently `0`              |
//! | `8..136` | 128-byte bitmap, 1024 bits (one per chunk in the 32x32 region) |
//!
//! Bit index is `local_z * 32 + local_x` (`local_x = chunk_x.rem_euclid(32)`, likewise for z),
//! and within a byte the bit is LSB-first: bit `i` lives at `bitmap[i / 8] & (1 << (i % 8))`. A
//! set bit means Oxide generated that chunk; a clear bit means it did not (vanilla Java, or the
//! chunk was never generated).
//!
//! # Honesty: this is a record of what Oxide wrote, not a live fact about the region
//!
//! The sidecar is updated only when Oxide itself writes a chunk. It has **no way to observe**
//! anything that happens to the region file through another path, and nothing re-validates it
//! against the region's actual contents. Concretely, it drifts from reality when:
//!
//! - The region file is deleted, trimmed, or regenerated by a tool (MCA Selector, a world reset)
//!   without also touching or deleting the sidecar.
//! - A world is copied/backed up without its sidecars (or with stale ones), e.g. onto a fresh
//!   server data directory.
//! - Vanilla Java regenerates a chunk in place — for instance, a plugin force-deletes and
//!   regenerates a single chunk directly through Minecraft's own chunk system.
//!
//! **Failure mode:** a chunk that reads back as "Oxide-generated" may no longer be — the sidecar
//! bit is stale, and the marker will keep saying "oxide" for terrain that a human or a Java plugin
//! since replaced. Treat [`is_oxide_generated`] as *"Oxide's own record says it wrote this"*, not
//! as ground truth about the chunk's current contents. Nothing in this module can distinguish
//! "still accurate" from "stale" — a caller who needs stronger assurance has to add its own check
//! (e.g. comparing the chunk's `LastUpdate`/`InhabitedTime` against expectations, or hashing
//! terrain against a re-generated reference).
//!
//! A cheap (unbuilt, not requested by this task) drift signal worth knowing about: compare the
//! sidecar's mtime against the region file's mtime. If the region file is newer than its sidecar,
//! something wrote to the region without going through this module's write paths, and every bit
//! in that sidecar should be treated as suspect until re-verified.

use std::fs;
use std::path::{Path, PathBuf};

use oxide_core::ChunkPos;

use crate::error::AnvilError;
use crate::lock::RegionGuard;
use crate::region::{self, atomic_write};

const MAGIC: &[u8; 4] = b"OXPV";
const FORMAT_VERSION: u8 = 1;
const SIDECAR_LEN: usize = 136;
const BITMAP_LEN: usize = 128;

/// In-memory 1024-bit provenance set for one region (32x32 chunks): which chunks in the region
/// were generated by Oxide. See the module docs for the exact bit layout and its honesty caveats.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProvenanceMap {
    bitmap: [u8; BITMAP_LEN],
}

impl Default for ProvenanceMap {
    fn default() -> Self {
        Self {
            bitmap: [0u8; BITMAP_LEN],
        }
    }
}

fn bit_index(pos: ChunkPos) -> usize {
    let local_x = pos.x.rem_euclid(32) as usize;
    let local_z = pos.z.rem_euclid(32) as usize;
    local_z * 32 + local_x
}

impl ProvenanceMap {
    pub fn new() -> Self {
        Self::default()
    }

    /// Whether `pos` is marked Oxide-generated. `pos` may be any chunk coordinate; only its
    /// position modulo 32 (via `rem_euclid`) is used, matching the region-local bit layout.
    pub fn get(&self, pos: ChunkPos) -> bool {
        let i = bit_index(pos);
        (self.bitmap[i / 8] & (1 << (i % 8))) != 0
    }

    /// Set or clear the bit for `pos`.
    pub fn set(&mut self, pos: ChunkPos, value: bool) {
        let i = bit_index(pos);
        if value {
            self.bitmap[i / 8] |= 1 << (i % 8);
        } else {
            self.bitmap[i / 8] &= !(1 << (i % 8));
        }
    }

    /// Number of chunks currently marked Oxide-generated (0..=1024).
    pub fn count_set(&self) -> u32 {
        self.bitmap.iter().map(|b| b.count_ones()).sum()
    }

    /// True if no chunk in this region is marked Oxide-generated.
    pub fn is_empty(&self) -> bool {
        self.bitmap.iter().all(|&b| b == 0)
    }

    fn to_bytes(&self) -> [u8; SIDECAR_LEN] {
        let mut buf = [0u8; SIDECAR_LEN];
        buf[0..4].copy_from_slice(MAGIC);
        buf[4] = FORMAT_VERSION;
        buf[5] = 0; // flags
        buf[6..8].copy_from_slice(&0u16.to_le_bytes()); // reserved
        buf[8..SIDECAR_LEN].copy_from_slice(&self.bitmap);
        buf
    }

    fn from_bytes(path: &Path, bytes: &[u8]) -> Result<Self, AnvilError> {
        if bytes.len() != SIDECAR_LEN {
            return Err(AnvilError::ProvenanceBadLength {
                path: path.to_path_buf(),
                len: bytes.len(),
            });
        }
        if &bytes[0..4] != MAGIC {
            return Err(AnvilError::ProvenanceBadMagic {
                path: path.to_path_buf(),
            });
        }
        let version = bytes[4];
        if version != FORMAT_VERSION {
            return Err(AnvilError::ProvenanceUnknownVersion {
                path: path.to_path_buf(),
                version,
            });
        }
        let mut bitmap = [0u8; BITMAP_LEN];
        bitmap.copy_from_slice(&bytes[8..SIDECAR_LEN]);
        Ok(Self { bitmap })
    }
}

/// The sidecar path for a region file: the region filename with `.oxide` appended, alongside it.
pub fn sidecar_path_for(region_path: &Path) -> PathBuf {
    let mut os = region_path.as_os_str().to_owned();
    os.push(".oxide");
    PathBuf::from(os)
}

/// Load the provenance sidecar at `path`. A missing file is not an error — it means no chunk in
/// that region has ever been marked, and yields an empty [`ProvenanceMap`]. A file that exists
/// but fails to parse (bad magic, unknown version, wrong length) is an error: silently treating a
/// corrupt sidecar as empty would misreport provenance for every chunk in the region.
pub fn load(path: &Path) -> Result<ProvenanceMap, AnvilError> {
    match fs::read(path) {
        Ok(bytes) => ProvenanceMap::from_bytes(path, &bytes),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(ProvenanceMap::default()),
        Err(e) => Err(AnvilError::Io(e)),
    }
}

/// Write the provenance sidecar to `path`, replacing whatever is there. Crash-safe: temp-file
/// then atomic rename, the same scheme [`crate::region::write_region_file`] uses for the region
/// file itself.
pub fn store(path: &Path, map: &ProvenanceMap) -> Result<(), AnvilError> {
    atomic_write(path, &map.to_bytes())
}

/// Read-modify-write the sidecar for `region_path` to set the bit for `pos`, without acquiring
/// [`RegionGuard`] — for callers that already hold the guard for `region_path` (the region write
/// paths in [`crate::region`]), so the sidecar update happens under the same critical section as
/// the region write it describes.
pub(crate) fn mark_chunk_locked(region_path: &Path, pos: ChunkPos) -> Result<(), AnvilError> {
    let sidecar = sidecar_path_for(region_path);
    let mut map = load(&sidecar)?;
    map.set(pos, true);
    store(&sidecar, &map)
}

/// Convenience: mark a single chunk as Oxide-generated, given the world's region directory and
/// the chunk's position. Acquires the same [`RegionGuard`] the region writers use, so this cannot
/// race a concurrent `write_region_file`/`update_chunk_in_place` call for the same region.
pub fn mark_chunk(region_dir: &Path, pos: ChunkPos) -> Result<(), AnvilError> {
    let region_path = region_dir.join(region::region_file_name(&pos));
    let _guard = RegionGuard::acquire(&region_path)?;
    mark_chunk_locked(&region_path, pos)
}

/// Read path for consumers (the pregen CLI, tests, the validation harness) that just want to
/// know whether Oxide's own records say it generated a given chunk. See the module docs' honesty
/// section: this reports what the sidecar says, which is not guaranteed to still be true.
pub fn is_oxide_generated(region_dir: &Path, pos: ChunkPos) -> Result<bool, AnvilError> {
    let region_path = region_dir.join(region::region_file_name(&pos));
    let sidecar = sidecar_path_for(&region_path);
    Ok(load(&sidecar)?.get(pos))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch_dir(name: &str) -> PathBuf {
        crate::test_support::scratch_dir(name)
    }

    #[test]
    fn new_map_is_empty() {
        let map = ProvenanceMap::new();
        assert!(map.is_empty());
        assert_eq!(map.count_set(), 0);
    }

    #[test]
    fn get_set_round_trip() {
        let mut map = ProvenanceMap::new();
        let pos = ChunkPos::new(5, 9);
        assert!(!map.get(pos));
        map.set(pos, true);
        assert!(map.get(pos));
        assert_eq!(map.count_set(), 1);
        map.set(pos, false);
        assert!(!map.get(pos));
        assert!(map.is_empty());
    }

    #[test]
    fn bit_indexing_four_corners() {
        // local (x=0,z=0) -> bit 0 -> bitmap[0] & 0x01
        let mut map = ProvenanceMap::new();
        map.set(ChunkPos::new(0, 0), true);
        assert_eq!(map.bitmap[0], 0x01);
        assert_eq!(map.count_set(), 1);

        // local (x=31,z=0) -> bit 31 -> bitmap[3] & 0x80
        let mut map = ProvenanceMap::new();
        map.set(ChunkPos::new(31, 0), true);
        assert_eq!(map.bitmap[3], 0x80);

        // local (x=0,z=31) -> bit 31*32=992 -> bitmap[124] & 0x01
        let mut map = ProvenanceMap::new();
        map.set(ChunkPos::new(0, 31), true);
        assert_eq!(map.bitmap[124], 0x01);

        // local (x=31,z=31) -> bit 31*32+31=1023 -> bitmap[127] & 0x80
        let mut map = ProvenanceMap::new();
        map.set(ChunkPos::new(31, 31), true);
        assert_eq!(map.bitmap[127], 0x80);
    }

    #[test]
    fn negative_coords_use_rem_euclid_not_percent() {
        // -1 rem_euclid 32 == 31 (Rust's `%` would give -1). Chunk (-1, -1) must land on the
        // same bit as chunk (31, 31): the region-local corner, not a negative/out-of-range index.
        let mut map = ProvenanceMap::new();
        map.set(ChunkPos::new(-1, -1), true);
        assert_eq!(map.bitmap[127], 0x80);
        assert!(map.get(ChunkPos::new(31, 31)));

        // Chunk (-32, -32) is local (0,0) of the region one below/left of the origin region.
        let mut map = ProvenanceMap::new();
        map.set(ChunkPos::new(-32, -32), true);
        assert_eq!(map.bitmap[0], 0x01);

        // A chunk two regions negative in x, one region negative in z: (-33, -33) -> local
        // (-33).rem_euclid(32) = 31, (-33).rem_euclid(32) = 31 -> same corner as (31,31).
        let mut map = ProvenanceMap::new();
        map.set(ChunkPos::new(-33, -33), true);
        assert_eq!(map.bitmap[127], 0x80);
    }

    #[test]
    fn store_then_load_round_trips() {
        let dir = scratch_dir("provenance-roundtrip");
        let path = dir.join("r.0.0.mca.oxide");

        let mut map = ProvenanceMap::new();
        map.set(ChunkPos::new(0, 0), true);
        map.set(ChunkPos::new(17, 22), true);
        map.set(ChunkPos::new(-1, -1), true);

        store(&path, &map).unwrap();
        let loaded = load(&path).unwrap();
        assert_eq!(loaded, map);
        assert_eq!(loaded.count_set(), 3);
    }

    #[test]
    fn store_writes_exact_byte_layout() {
        let dir = scratch_dir("provenance-layout");
        let path = dir.join("r.0.0.mca.oxide");

        let mut map = ProvenanceMap::new();
        map.set(ChunkPos::new(0, 0), true);
        store(&path, &map).unwrap();

        let bytes = fs::read(&path).unwrap();
        assert_eq!(bytes.len(), SIDECAR_LEN);
        assert_eq!(&bytes[0..4], b"OXPV");
        assert_eq!(bytes[4], 1); // version
        assert_eq!(bytes[5], 0); // flags
        assert_eq!(&bytes[6..8], &[0, 0]); // reserved
        assert_eq!(bytes[8], 0x01); // bit 0 set
        assert!(bytes[9..136].iter().all(|&b| b == 0));
    }

    #[test]
    fn missing_file_yields_empty_map_not_error() {
        let dir = scratch_dir("provenance-missing");
        let path = dir.join("r.0.0.mca.oxide");
        assert!(!path.exists());

        let map = load(&path).unwrap();
        assert!(map.is_empty());
    }

    #[test]
    fn bad_magic_is_an_error() {
        let dir = scratch_dir("provenance-bad-magic");
        let path = dir.join("r.0.0.mca.oxide");
        let mut bytes = vec![0u8; SIDECAR_LEN];
        bytes[0..4].copy_from_slice(b"NOPE");
        bytes[4] = 1;
        fs::write(&path, &bytes).unwrap();

        let err = load(&path).unwrap_err();
        assert!(matches!(err, AnvilError::ProvenanceBadMagic { .. }));
    }

    #[test]
    fn unknown_version_is_an_error() {
        let dir = scratch_dir("provenance-bad-version");
        let path = dir.join("r.0.0.mca.oxide");
        let mut bytes = vec![0u8; SIDECAR_LEN];
        bytes[0..4].copy_from_slice(MAGIC);
        bytes[4] = 99;
        fs::write(&path, &bytes).unwrap();

        let err = load(&path).unwrap_err();
        assert!(matches!(
            err,
            AnvilError::ProvenanceUnknownVersion { version: 99, .. }
        ));
    }

    #[test]
    fn truncated_file_is_an_error() {
        let dir = scratch_dir("provenance-truncated");
        let path = dir.join("r.0.0.mca.oxide");
        let mut bytes = vec![0u8; 40]; // too short
        bytes[0..4].copy_from_slice(MAGIC);
        bytes[4] = 1;
        fs::write(&path, &bytes).unwrap();

        let err = load(&path).unwrap_err();
        assert!(matches!(
            err,
            AnvilError::ProvenanceBadLength { len: 40, .. }
        ));
    }

    #[test]
    fn sidecar_path_appends_oxide_suffix() {
        let region = PathBuf::from("/worlds/foo/region/r.3.-2.mca");
        let sidecar = sidecar_path_for(&region);
        assert_eq!(
            sidecar,
            PathBuf::from("/worlds/foo/region/r.3.-2.mca.oxide")
        );
    }
}
