//! Loading vanilla-generated chunks to diff Oxide's output against.
//!
//! A reference world is an ordinary Minecraft world directory generated by a real server. This
//! reads its region files back into the same [`ChunkData`] shape Oxide produces, so both sides
//! go through one Merkle implementation and a mismatch means a real difference in placed blocks
//! rather than a difference in how the two were represented.
//!
//! Reference worlds are gitignored and must never be committed or redistributed -- they are
//! derived from the game's own output. See `docs/REFERENCE_DATA.md`.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use oxide_anvil::nbt::{parse_chunk, SectionNbt};
use oxide_anvil::region;
use oxide_core::{BlockState, ChunkData, ChunkPos, ChunkSection, ResourceLocation};

/// Why a reference chunk could not be loaded. Distinguishes "not generated" from "unreadable":
/// a missing chunk is a reason to skip it, a malformed one is a reason to stop.
#[derive(Debug)]
pub enum ReferenceError {
    Io(std::io::Error),
    Anvil(oxide_anvil::AnvilError),
    /// A block state name in the reference palette is not a valid resource location.
    BadBlockName {
        chunk: ChunkPos,
        name: String,
    },
    /// The packed index array is not the length the palette and section size imply.
    BadPacking {
        chunk: ChunkPos,
        section_y: i8,
        detail: String,
    },
}

impl std::fmt::Display for ReferenceError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ReferenceError::Io(e) => write!(f, "reading the reference world: {e}"),
            ReferenceError::Anvil(e) => write!(f, "decoding a reference region: {e}"),
            ReferenceError::BadBlockName { chunk, name } => write!(
                f,
                "reference chunk {},{} has an unparseable block name {name:?}",
                chunk.x, chunk.z
            ),
            ReferenceError::BadPacking {
                chunk,
                section_y,
                detail,
            } => write!(
                f,
                "reference chunk {},{} section {section_y}: {detail}",
                chunk.x, chunk.z
            ),
        }
    }
}

impl std::error::Error for ReferenceError {}

impl From<std::io::Error> for ReferenceError {
    fn from(e: std::io::Error) -> Self {
        ReferenceError::Io(e)
    }
}

impl From<oxide_anvil::AnvilError> for ReferenceError {
    fn from(e: oxide_anvil::AnvilError) -> Self {
        ReferenceError::Anvil(e)
    }
}

/// A vanilla-generated world on disk.
pub struct ReferenceWorld {
    region_dir: PathBuf,
}

impl ReferenceWorld {
    /// `world_dir` is the world folder itself; the overworld's regions live in `region/` beneath
    /// it, other dimensions under `DIM-1/region` and so on.
    pub fn open(world_dir: &Path, dimension_subdir: Option<&str>) -> Result<Self, ReferenceError> {
        let region_dir = match dimension_subdir {
            Some(sub) => world_dir.join(sub).join("region"),
            None => world_dir.join("region"),
        };
        if !region_dir.is_dir() {
            return Err(ReferenceError::Io(std::io::Error::new(
                std::io::ErrorKind::NotFound,
                format!("no region directory at {}", region_dir.display()),
            )));
        }
        Ok(Self { region_dir })
    }

    /// Reads one chunk, or `None` when the reference world never generated it.
    pub fn chunk(&self, pos: ChunkPos) -> Result<Option<ChunkData>, ReferenceError> {
        let path = self.region_dir.join(region::region_file_name(&pos));
        let Some(bytes) = region::read_chunk(&path, &pos)? else {
            return Ok(None);
        };
        let root = parse_chunk(&bytes)?;

        // Height comes from the sections present rather than from a preset: the reference world
        // is the authority on its own shape, and reading it from anywhere else would let a
        // mismatched datapack silently pass.
        let Some(min_section) = root.sections.iter().map(|s| s.y).min() else {
            return Ok(None);
        };
        let max_section = root.sections.iter().map(|s| s.y).max().unwrap();
        let min_y = min_section as i32 * 16;
        let height = (max_section as i32 - min_section as i32 + 1) * 16;

        let mut chunk = ChunkData::new(pos, min_y, height);
        let mut sections: Vec<&SectionNbt> = root.sections.iter().collect();
        sections.sort_by_key(|s| s.y);
        for section in sections {
            chunk.sections.push(decode_section(pos, section)?);
        }
        Ok(Some(chunk))
    }
}

/// Turns one NBT section into the in-memory form, expanding the packed index array.
fn decode_section(pos: ChunkPos, nbt: &SectionNbt) -> Result<ChunkSection, ReferenceError> {
    let palette: Vec<BlockState> = nbt
        .block_states
        .palette
        .iter()
        .map(|entry| {
            let name: ResourceLocation =
                entry
                    .name
                    .parse()
                    .map_err(|_| ReferenceError::BadBlockName {
                        chunk: pos,
                        name: entry.name.clone(),
                    })?;
            Ok(BlockState {
                name,
                properties: entry
                    .properties
                    .clone()
                    .unwrap_or_else(BTreeMap::new)
                    .into_iter()
                    .collect(),
            })
        })
        .collect::<Result<_, ReferenceError>>()?;

    if palette.is_empty() {
        return Err(ReferenceError::BadPacking {
            chunk: pos,
            section_y: nbt.y,
            detail: "empty block palette".into(),
        });
    }

    // Biomes are not compared here. Vanilla writes them at a different granularity and Oxide's
    // biome parity has its own check; mixing them in would make a block mismatch and a biome
    // mismatch indistinguishable in the same tree.
    let air = BlockState::new(ResourceLocation::minecraft("air"));
    let plains = ResourceLocation::minecraft("plains");
    let mut section = ChunkSection::new(nbt.y, air, plains);

    match &nbt.block_states.data {
        // A uniform section carries no data array at all -- every position is palette entry 0.
        None => {
            if palette.len() != 1 {
                return Err(ReferenceError::BadPacking {
                    chunk: pos,
                    section_y: nbt.y,
                    detail: format!(
                        "no packed data but the palette holds {} entries; only a single-entry \
                         palette may omit it",
                        palette.len()
                    ),
                });
            }
            for i in 0..4096 {
                section.block_states.set(i, palette[0].clone());
            }
        }
        Some(data) => {
            let indices = unpack(
                data.iter().copied().collect::<Vec<i64>>().as_slice(),
                palette.len(),
                4096,
            )
            .map_err(|detail| ReferenceError::BadPacking {
                chunk: pos,
                section_y: nbt.y,
                detail,
            })?;
            for (i, index) in indices.into_iter().enumerate() {
                let state =
                    palette
                        .get(index as usize)
                        .ok_or_else(|| ReferenceError::BadPacking {
                            chunk: pos,
                            section_y: nbt.y,
                            detail: format!(
                                "index {index} at position {i} is outside a {}-entry palette",
                                palette.len()
                            ),
                        })?;
                section.block_states.set(i, state.clone());
            }
        }
    }

    Ok(section)
}

/// Expands Minecraft's packed index array.
///
/// Entries do not straddle longs: each long holds `64 / bits` entries and any leftover high bits
/// are padding. Unpacking as a continuous bit stream instead is the classic way to read a chunk
/// that looks almost right, so this follows the padded layout deliberately.
fn unpack(data: &[i64], palette_len: usize, count: usize) -> Result<Vec<u32>, String> {
    let bits = bits_per_entry(palette_len);
    let per_long = 64 / bits;
    let expected_longs = count.div_ceil(per_long);
    if data.len() != expected_longs {
        return Err(format!(
            "packed data is {} longs, expected {expected_longs} for {count} entries at {bits} \
             bits each",
            data.len()
        ));
    }

    let mask = (1u64 << bits) - 1;
    let mut out = Vec::with_capacity(count);
    for i in 0..count {
        let long = data[i / per_long] as u64;
        let shift = (i % per_long) * bits;
        out.push(((long >> shift) & mask) as u32);
    }
    Ok(out)
}

/// Bits per index for a palette of this size, with vanilla's floor of 4 for block states.
fn bits_per_entry(palette_len: usize) -> usize {
    let needed = usize::BITS - (palette_len.max(2) - 1).leading_zeros();
    (needed as usize).max(4)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn palette_sizes_map_to_vanilla_bit_widths() {
        // Floor of 4 bits holds up to 16 entries; then one more bit per doubling.
        assert_eq!(bits_per_entry(1), 4);
        assert_eq!(bits_per_entry(2), 4);
        assert_eq!(bits_per_entry(16), 4);
        assert_eq!(bits_per_entry(17), 5);
        assert_eq!(bits_per_entry(32), 5);
        assert_eq!(bits_per_entry(33), 6);
        assert_eq!(bits_per_entry(256), 8);
        assert_eq!(bits_per_entry(257), 9);
    }

    /// Entries are padded within each long rather than spanning them -- 5-bit entries pack 12 to
    /// a long and leave 4 bits unused, they do not continue into the next long.
    #[test]
    fn unpacks_with_padding_not_as_a_bit_stream() {
        let bits = 5;
        let per_long = 64 / bits; // 12
        let count: usize = 4096;
        let longs = count.div_ceil(per_long);
        let mut data = vec![0i64; longs];
        // Put a distinct value at the last slot of the first long and the first of the second.
        let last_of_first = per_long - 1;
        data[0] = ((7u64) << (last_of_first * bits)) as i64;
        data[1] = 9i64;

        let out = unpack(&data, 17, count).expect("unpacks");
        assert_eq!(out[last_of_first], 7);
        assert_eq!(out[per_long], 9);
        // The padding bits above the last entry in a long must not leak into the next entry.
        assert_eq!(out[last_of_first - 1], 0);
    }

    #[test]
    fn rejects_a_wrongly_sized_array() {
        assert!(unpack(&[0i64; 3], 17, 4096).is_err());
    }
}
