//! Jigsaw structure assembly: villages, outposts, bastions, ancient cities, trial chambers.
//!
//! A port of 26.2's `JigsawPlacement` — `addPieces` and `Placer.tryPlacingChildren` — from the
//! decompiled game rather than from a description of it. What that buys, in the order the
//! algorithm cares about:
//!
//! - **Rotation.** A piece is placed under one of four rotations, and the connector positions and
//!   facings turn with it (`crate::rotation`, `StructureTemplate::jigsaws_at`).
//! - **Connector matching.** A candidate attaches only when its front faces the opposite way, its
//!   `name` equals the source's `target`, and — for an `aligned` joint — the two tops agree. That
//!   is `JigsawBlock.canAttach`, and it is why a village road meets a house door rather than its
//!   roof.
//! - **Origin offset.** The child is positioned so its own connector lands on the block the
//!   source's connector points at, not at the source's connector.
//! - **Free space.** Vanilla keeps a `VoxelShape` of the space still available and requires a
//!   candidate's box to fit entirely inside it. Since that shape only ever starts as one box and
//!   has boxes subtracted from it, [`FreeRegion`] represents it exactly as a limit box minus a
//!   list of occupied boxes — same answers, no voxel grid.
//! - **Expansion order.** Connectors are expanded highest-`placement_priority` first, FIFO within
//!   a priority ([`PriorityQueue`], vanilla's `SequencedPriorityIterator`), which is what keeps a
//!   village's roads ahead of its houses.
//! - **Terrain matching.** A `terrain_matching` piece is dropped onto the surface instead of
//!   hanging off its connector's Y.
//!
//! Every RNG draw is placed where vanilla places it — the rotation shuffles, the two pool
//! shuffles, the per-piece connector shuffle — because the draw *order* is what makes a seed
//! reproduce. PARITY-CHECK: that ordering is transcribed from the decompile and unit-tested for
//! self-consistency, but has never been diffed against a village generated by the real game;
//! `docs/ROADMAP.md` tracks that as the gate before any parity claim.
//!
//! Not ported, and each one is a divergence rather than a shortcut: `list` and `feature` pool
//! elements, structure processors (`processors` is parsed and ignored), pool aliases, the
//! `start_jigsaw_name` anchor, dimension padding, and liquid settings.

use std::cell::RefCell;
use std::collections::HashMap;
use std::rc::Rc;

use oxide_core::{BlockPos, BlockState, ChunkData, ChunkPos, RandomSource, ResourceLocation};

use crate::pool::{PoolElement, Projection, TemplatePool};
use crate::rotation::Rotation;
use crate::template::{JigsawConnector, JigsawJoint, StructureTemplate};

/// An Axis-Aligned 3D Bounding Box, inclusive on both ends like vanilla's `BoundingBox`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BoundingBox {
    pub min_x: i32,
    pub min_y: i32,
    pub min_z: i32,
    pub max_x: i32,
    pub max_y: i32,
    pub max_z: i32,
}

impl BoundingBox {
    pub fn new(min_x: i32, min_y: i32, min_z: i32, max_x: i32, max_y: i32, max_z: i32) -> Self {
        Self {
            min_x,
            min_y,
            min_z,
            max_x,
            max_y,
            max_z,
        }
    }

    pub fn intersects(&self, other: &BoundingBox) -> bool {
        self.max_x >= other.min_x
            && self.min_x <= other.max_x
            && self.max_y >= other.min_y
            && self.min_y <= other.max_y
            && self.max_z >= other.min_z
            && self.min_z <= other.max_z
    }

    pub fn contains_point(&self, x: i32, y: i32, z: i32) -> bool {
        x >= self.min_x
            && x <= self.max_x
            && y >= self.min_y
            && y <= self.max_y
            && z >= self.min_z
            && z <= self.max_z
    }

    pub fn contains(&self, pos: BlockPos) -> bool {
        self.contains_point(pos.x, pos.y, pos.z)
    }

    pub fn contains_box(&self, other: &BoundingBox) -> bool {
        other.min_x >= self.min_x
            && other.max_x <= self.max_x
            && other.min_y >= self.min_y
            && other.max_y <= self.max_y
            && other.min_z >= self.min_z
            && other.max_z <= self.max_z
    }

    pub fn moved(&self, dx: i32, dy: i32, dz: i32) -> Self {
        Self::new(
            self.min_x + dx,
            self.min_y + dy,
            self.min_z + dz,
            self.max_x + dx,
            self.max_y + dy,
            self.max_z + dz,
        )
    }

    /// Vanilla's `getYSpan`: inclusive, so a one-block-tall box spans 1.
    pub fn y_span(&self) -> i32 {
        self.max_y - self.min_y + 1
    }
}

/// The space a piece may still be placed into.
///
/// Vanilla carries a `VoxelShape` and asks `Shapes.joinIsNotEmpty(free, box.deflate(0.25),
/// ONLY_SECOND)` — "is any part of this box outside the free space?" — then subtracts the box it
/// accepted. Because the shape is only ever one box with boxes subtracted from it, that question
/// is exactly "inside the limit, and touching none of the occupied boxes". The `deflate(0.25)` is
/// what makes two boxes sharing a face legal while a one-block overlap is not, which is what an
/// inclusive integer intersection test already says.
#[derive(Debug, Clone)]
pub struct FreeRegion {
    pub limit: BoundingBox,
    pub occupied: Vec<BoundingBox>,
}

impl FreeRegion {
    pub fn new(limit: BoundingBox) -> Self {
        Self {
            limit,
            occupied: Vec::new(),
        }
    }

    pub fn accepts(&self, candidate: &BoundingBox) -> bool {
        self.limit.contains_box(candidate)
            && !self.occupied.iter().any(|taken| taken.intersects(candidate))
    }

    pub fn take(&mut self, taken: BoundingBox) {
        self.occupied.push(taken);
    }
}

/// A placed structure piece: which template, where, and turned which way.
#[derive(Debug, Clone)]
pub struct AssembledPiece {
    pub template: ResourceLocation,
    pub origin: BlockPos,
    pub rotation: Rotation,
    pub bbox: BoundingBox,
    pub blocks: Vec<(BlockPos, BlockState)>,
}

/// A complete assembled structure — every piece the jigsaw walk reached.
#[derive(Debug, Clone)]
pub struct AssembledStructure {
    pub start_pos: BlockPos,
    pub pieces: Vec<AssembledPiece>,
    pub overall_bbox: BoundingBox,
}

impl AssembledStructure {
    pub fn new(start_pos: BlockPos) -> Self {
        Self {
            start_pos,
            pieces: Vec::new(),
            overall_bbox: BoundingBox::new(
                start_pos.x,
                start_pos.y,
                start_pos.z,
                start_pos.x,
                start_pos.y,
                start_pos.z,
            ),
        }
    }

    pub fn add_piece(&mut self, piece: AssembledPiece) {
        self.overall_bbox.min_x = self.overall_bbox.min_x.min(piece.bbox.min_x);
        self.overall_bbox.min_y = self.overall_bbox.min_y.min(piece.bbox.min_y);
        self.overall_bbox.min_z = self.overall_bbox.min_z.min(piece.bbox.min_z);
        self.overall_bbox.max_x = self.overall_bbox.max_x.max(piece.bbox.max_x);
        self.overall_bbox.max_y = self.overall_bbox.max_y.max(piece.bbox.max_y);
        self.overall_bbox.max_z = self.overall_bbox.max_z.max(piece.bbox.max_z);
        self.pieces.push(piece);
    }

    /// Whether any of this structure could land in `pos`'s column. Cheap enough to ask before
    /// paying for [`Self::stamp_into_chunk`], which repeats the same rejection internally.
    pub fn overall_bbox_intersects_chunk(&self, pos: ChunkPos) -> bool {
        let min_x = pos.min_block_x();
        let min_z = pos.min_block_z();
        self.overall_bbox.max_x >= min_x
            && self.overall_bbox.min_x <= min_x + 15
            && self.overall_bbox.max_z >= min_z
            && self.overall_bbox.min_z <= min_z + 15
    }

    /// Stitches blocks of this structure that fall within `chunk` into the chunk's sections.
    pub fn stamp_into_chunk(&self, chunk: &mut ChunkData, pos: ChunkPos) {
        let chunk_min_x = pos.min_block_x();
        let chunk_max_x = chunk_min_x + 15;
        let chunk_min_z = pos.min_block_z();
        let chunk_max_z = chunk_min_z + 15;

        if self.overall_bbox.max_x < chunk_min_x
            || self.overall_bbox.min_x > chunk_max_x
            || self.overall_bbox.max_z < chunk_min_z
            || self.overall_bbox.min_z > chunk_max_z
        {
            return;
        }

        for piece in &self.pieces {
            if piece.bbox.max_x < chunk_min_x
                || piece.bbox.min_x > chunk_max_x
                || piece.bbox.max_z < chunk_min_z
                || piece.bbox.min_z > chunk_max_z
            {
                continue;
            }

            for (bpos, state) in &piece.blocks {
                if bpos.x < chunk_min_x
                    || bpos.x > chunk_max_x
                    || bpos.z < chunk_min_z
                    || bpos.z > chunk_max_z
                {
                    continue;
                }
                let y = bpos.y;
                if y < chunk.min_y || y >= chunk.min_y + chunk.height {
                    continue;
                }

                let section_idx = ((y - chunk.min_y) / 16) as usize;
                if section_idx >= chunk.sections.len() {
                    continue;
                }

                let local_x = (bpos.x - chunk_min_x) as usize;
                let local_z = (bpos.z - chunk_min_z) as usize;
                let local_y = (y - chunk.min_y).rem_euclid(16) as usize;
                let slot = (local_y * 16 + local_z) * 16 + local_x;
                chunk.sections[section_idx]
                    .block_states
                    .set(slot, state.clone());
            }
        }
    }
}

/// What the assembler needs from the datapack: templates by id, pools by id.
pub trait TemplateSource {
    fn template(&self, id: &ResourceLocation) -> Option<&StructureTemplate>;
    fn pool(&self, id: &ResourceLocation) -> Option<&TemplatePool>;
}

/// `ChunkGenerator.getFirstFreeHeight(x, z, WORLD_SURFACE_WG)` — the surface a
/// `terrain_matching` piece is dropped onto, and the reference height for junctions between
/// pieces that are not both rigid.
pub trait SurfaceHeights {
    fn first_free_height(&self, x: i32, z: i32) -> i32;
}

/// The knobs `JigsawStructure` passes into placement.
#[derive(Debug, Clone)]
pub struct JigsawSettings {
    pub max_depth: i32,
    /// `MaxDistance`: how far from the centre a piece may reach, horizontally and vertically.
    pub max_distance_horizontal: i32,
    pub max_distance_vertical: i32,
    /// Vanilla's `doExpansionHack`, on for villages: reserves headroom above a short piece so a
    /// tall child can still attach later.
    pub do_expansion_hack: bool,
    /// When set, the start piece is dropped onto the surface (`project_start_to_heightmap`).
    pub project_start_to_heightmap: bool,
    pub min_y: i32,
    pub max_y: i32,
}

impl Default for JigsawSettings {
    fn default() -> Self {
        Self {
            max_depth: 6,
            max_distance_horizontal: 80,
            max_distance_vertical: 80,
            do_expansion_hack: false,
            project_start_to_heightmap: true,
            min_y: -64,
            max_y: 319,
        }
    }
}

/// Vanilla's `getGroundLevelDelta()`, which every pool element inherits and none overrides.
const GROUND_LEVEL_DELTA: i32 = 1;

/// `JigsawBlock.canAttach`.
fn can_attach(source: &JigsawConnector, target: &JigsawConnector) -> bool {
    source.front == target.front.opposite()
        && (source.joint == JigsawJoint::Rollable || source.top == target.top)
        && source.target == target.name
}

/// `SinglePoolElement.getShuffledJigsawBlocks`: shuffle, then stable-sort highest
/// `selection_priority` first. Both steps matter — the shuffle decides ties, the sort decides
/// which connector a piece offers up first.
fn shuffled_jigsaws(
    template: &StructureTemplate,
    position: BlockPos,
    rotation: Rotation,
    random: &mut impl RandomSource,
) -> Vec<JigsawConnector> {
    let mut jigsaws = template.jigsaws_at(position, rotation);
    crate::rotation::shuffle(&mut jigsaws, random);
    jigsaws.sort_by_key(|jigsaw| std::cmp::Reverse(jigsaw.selection_priority));
    jigsaws
}

/// Vanilla's `SequencedPriorityIterator`: highest priority first, insertion order within one
/// priority.
#[derive(Debug)]
struct PriorityQueue<T> {
    queues: Vec<(i32, std::collections::VecDeque<T>)>,
}

impl<T> Default for PriorityQueue<T> {
    fn default() -> Self {
        Self { queues: Vec::new() }
    }
}

impl<T> PriorityQueue<T> {
    fn add(&mut self, item: T, priority: i32) {
        match self.queues.iter_mut().find(|(p, _)| *p == priority) {
            Some((_, queue)) => queue.push_back(item),
            None => {
                let mut queue = std::collections::VecDeque::new();
                queue.push_back(item);
                self.queues.push((priority, queue));
            }
        }
    }

    fn next(&mut self) -> Option<T> {
        let best = self
            .queues
            .iter_mut()
            .filter(|(_, queue)| !queue.is_empty())
            .max_by_key(|(priority, _)| *priority)?;
        best.1.pop_front()
    }
}

struct PieceState {
    piece: usize,
    free: Rc<RefCell<FreeRegion>>,
    depth: i32,
}

/// Assembles a jigsaw structure whose start pool is `start_pool`, anchored at `position`.
///
/// Returns `None` when the start pool is missing, empty, or resolves to a template the pack does
/// not ship — the same cases where vanilla logs and places nothing.
pub fn assemble_jigsaw(
    start_pool: &ResourceLocation,
    position: BlockPos,
    settings: &JigsawSettings,
    random: &mut impl RandomSource,
    source: &impl TemplateSource,
    heights: &impl SurfaceHeights,
) -> Option<AssembledStructure> {
    // Draw order matters from the first line: vanilla takes the rotation before the element.
    let center_rotation = Rotation::get_random(random);
    let pool = source.pool(start_pool)?;
    let center_element = pool.random_template(random)?;
    if center_element.is_empty() {
        return None;
    }
    let center_template_id = center_element.template()?.clone();
    let center_template = source.template(&center_template_id)?;

    let mut center_bbox = center_template.bounding_box(position, center_rotation);
    let mut center_position = position;

    // `projectStartToHeightmap`: drop the start piece so its ground level sits on the surface.
    if settings.project_start_to_heightmap {
        let center_x = (center_bbox.max_x + center_bbox.min_x) / 2;
        let center_z = (center_bbox.max_z + center_bbox.min_z) / 2;
        let bottom_y = position.y + heights.first_free_height(center_x, center_z);
        let old_ground_y = center_bbox.min_y + GROUND_LEVEL_DELTA;
        let shift = bottom_y - old_ground_y;
        center_bbox = center_bbox.moved(0, shift, 0);
        center_position = BlockPos::new(position.x, position.y + shift, position.z);
    }

    let mut structure = AssembledStructure::new(center_position);
    structure.add_piece(AssembledPiece {
        template: center_template_id,
        origin: center_position,
        rotation: center_rotation,
        bbox: center_bbox,
        blocks: center_template.blocks_at(center_position, center_rotation),
    });

    if settings.max_depth <= 0 {
        return Some(structure);
    }

    let center_x = (center_bbox.max_x + center_bbox.min_x) / 2;
    let center_y = center_bbox.min_y;
    let center_z = (center_bbox.max_z + center_bbox.min_z) / 2;
    let limit = BoundingBox::new(
        center_x - settings.max_distance_horizontal,
        (center_y - settings.max_distance_vertical).max(settings.min_y),
        center_z - settings.max_distance_horizontal,
        center_x + settings.max_distance_horizontal,
        (center_y + settings.max_distance_vertical).min(settings.max_y),
        center_z + settings.max_distance_horizontal,
    );
    let mut free = FreeRegion::new(limit);
    free.take(center_bbox);

    let mut placer = Placer {
        settings,
        source,
        heights,
        projections: HashMap::new(),
        queue: PriorityQueue::default(),
    };
    placer.projections.insert(0, center_element.projection());

    let root_free = Rc::new(RefCell::new(free));
    placer.try_placing_children(&mut structure, 0, &root_free, 0, random);
    while let Some(state) = placer.queue.next() {
        placer.try_placing_children(&mut structure, state.piece, &state.free, state.depth, random);
    }

    Some(structure)
}

struct Placer<'a, S: TemplateSource, H: SurfaceHeights> {
    settings: &'a JigsawSettings,
    source: &'a S,
    heights: &'a H,
    /// A piece's projection is needed again when its own children are placed, and it is not
    /// recoverable from the piece itself.
    projections: HashMap<usize, Projection>,
    queue: PriorityQueue<PieceState>,
}

impl<S: TemplateSource, H: SurfaceHeights> Placer<'_, S, H> {
    fn try_placing_children(
        &mut self,
        structure: &mut AssembledStructure,
        source_index: usize,
        context_free: &Rc<RefCell<FreeRegion>>,
        depth: i32,
        random: &mut impl RandomSource,
    ) {
        let (source_template_id, source_position, source_rotation, source_bb) = {
            let piece = &structure.pieces[source_index];
            (
                piece.template.clone(),
                piece.origin,
                piece.rotation,
                piece.bbox,
            )
        };
        let Some(source_template) = self.source.template(&source_template_id) else {
            return;
        };
        let source_projection = self
            .projections
            .get(&source_index)
            .copied()
            .unwrap_or(Projection::Rigid);
        let source_rigid = source_projection == Projection::Rigid;
        let source_box_y = source_bb.min_y;
        // Connections that stay inside the source piece share one free region, created lazily and
        // limited to the source's own box.
        let mut source_free: Option<Rc<RefCell<FreeRegion>>> = None;

        for source_jigsaw in shuffled_jigsaws(source_template, source_position, source_rotation, random)
        {
            let source_direction = source_jigsaw.front;
            let source_jigsaw_pos = source_jigsaw.pos;
            let target_jigsaw_pos = BlockPos::new(
                source_jigsaw_pos.x + source_direction.step_x(),
                source_jigsaw_pos.y + source_direction.step_y(),
                source_jigsaw_pos.z + source_direction.step_z(),
            );
            let source_jigsaw_local_y = source_jigsaw_pos.y - source_box_y;
            let mut source_jigsaw_base_height: Option<i32> = None;

            let Some(target_pool) = self.source.pool(&source_jigsaw.pool) else {
                continue;
            };
            if target_pool.size() == 0 && source_jigsaw.pool.path() != "empty" {
                continue;
            }
            let fallback_id = target_pool.fallback.clone();
            let fallback = fallback_id.as_ref().and_then(|id| self.source.pool(id));
            if let (Some(id), Some(pool)) = (&fallback_id, fallback) {
                if pool.size() == 0 && id.path() != "empty" {
                    continue;
                }
            }

            let attach_inside_source = source_bb.contains(target_jigsaw_pos);
            let children_free = if attach_inside_source {
                source_free
                    .get_or_insert_with(|| Rc::new(RefCell::new(FreeRegion::new(source_bb))))
                    .clone()
            } else {
                context_free.clone()
            };

            // Both shuffles happen whether or not a candidate is ever accepted, so they are drawn
            // here rather than lazily inside the loop.
            let mut candidates: Vec<PoolElement> = Vec::new();
            if depth != self.settings.max_depth {
                candidates.extend(target_pool.shuffled_templates(random).into_iter().cloned());
            }
            if let Some(fallback) = fallback {
                candidates.extend(fallback.shuffled_templates(random).into_iter().cloned());
            }

            let placement_priority = source_jigsaw.placement_priority;

            'candidates: for target_element in &candidates {
                if target_element.is_empty() {
                    break;
                }
                let Some(target_template_id) = target_element.template() else {
                    continue;
                };
                let Some(target_template) = self.source.template(target_template_id) else {
                    continue;
                };

                for target_rotation in Rotation::get_shuffled(random) {
                    let target_jigsaws = shuffled_jigsaws(
                        target_template,
                        BlockPos::new(0, 0, 0),
                        target_rotation,
                        random,
                    );
                    let hack_box = target_template.bounding_box(BlockPos::new(0, 0, 0), target_rotation);
                    let expand_to = if self.settings.do_expansion_hack && hack_box.y_span() <= 16 {
                        self.expansion_headroom(&target_jigsaws, &hack_box)
                    } else {
                        0
                    };

                    for target_jigsaw in &target_jigsaws {
                        if !can_attach(&source_jigsaw, target_jigsaw) {
                            continue;
                        }

                        let target_jigsaw_local = target_jigsaw.pos;
                        let raw_target_position = BlockPos::new(
                            target_jigsaw_pos.x - target_jigsaw_local.x,
                            target_jigsaw_pos.y - target_jigsaw_local.y,
                            target_jigsaw_pos.z - target_jigsaw_local.z,
                        );
                        let raw_target_bb =
                            target_template.bounding_box(raw_target_position, target_rotation);
                        let target_projection = target_element.projection();
                        let target_rigid = target_projection == Projection::Rigid;
                        let target_jigsaw_local_y = target_jigsaw_local.y;
                        let delta_y = source_jigsaw_local_y - target_jigsaw_local_y
                            + source_direction.step_y();

                        let target_box_y = if source_rigid && target_rigid {
                            source_box_y + delta_y
                        } else {
                            let base = *source_jigsaw_base_height.get_or_insert_with(|| {
                                self.heights
                                    .first_free_height(source_jigsaw_pos.x, source_jigsaw_pos.z)
                            });
                            base - target_jigsaw_local_y
                        };

                        let y_offset = target_box_y - raw_target_bb.min_y;
                        let mut target_bb = raw_target_bb.moved(0, y_offset, 0);
                        let target_position = BlockPos::new(
                            raw_target_position.x,
                            raw_target_position.y + y_offset,
                            raw_target_position.z,
                        );
                        if expand_to > 0 {
                            let new_size = (expand_to + 1).max(target_bb.max_y - target_bb.min_y);
                            target_bb.max_y = target_bb.max_y.max(target_bb.min_y + new_size);
                        }

                        if !children_free.borrow().accepts(&target_bb) {
                            continue;
                        }
                        children_free.borrow_mut().take(target_bb);

                        let piece_index = structure.pieces.len();
                        structure.add_piece(AssembledPiece {
                            template: target_template_id.clone(),
                            origin: target_position,
                            rotation: target_rotation,
                            bbox: target_bb,
                            blocks: target_template.blocks_at(target_position, target_rotation),
                        });
                        self.projections.insert(piece_index, target_projection);

                        // Vanilla's `depth + 1 <= maxDepth`, kept in its own terms.
                        #[allow(clippy::int_plus_one)]
                        if depth + 1 <= self.settings.max_depth {
                            self.queue.add(
                                PieceState {
                                    piece: piece_index,
                                    free: children_free.clone(),
                                    depth: depth + 1,
                                },
                                placement_priority,
                            );
                        }
                        // Vanilla's `continue label129`: one connector places at most one child.
                        continue 'candidates;
                    }
                }
            }
        }
    }

    /// The expansion hack: how much headroom to reserve above a short piece, taken from the
    /// tallest thing its own connectors could later pull in.
    fn expansion_headroom(&self, jigsaws: &[JigsawConnector], hack_box: &BoundingBox) -> i32 {
        jigsaws
            .iter()
            .map(|jigsaw| {
                let ahead = BlockPos::new(
                    jigsaw.pos.x + jigsaw.front.step_x(),
                    jigsaw.pos.y + jigsaw.front.step_y(),
                    jigsaw.pos.z + jigsaw.front.step_z(),
                );
                if !hack_box.contains(ahead) {
                    return 0;
                }
                let pool = self.source.pool(&jigsaw.pool);
                let pool_size = pool.map(|p| self.max_pool_y_span(p)).unwrap_or(0);
                let fallback_size = pool
                    .and_then(|p| p.fallback.as_ref())
                    .and_then(|id| self.source.pool(id))
                    .map(|p| self.max_pool_y_span(p))
                    .unwrap_or(0);
                pool_size.max(fallback_size)
            })
            .max()
            .unwrap_or(0)
    }

    /// `StructureTemplatePool.getMaxSize`: the tallest unrotated element in the pool.
    fn max_pool_y_span(&self, pool: &TemplatePool) -> i32 {
        pool.expanded()
            .iter()
            .filter_map(|element| element.template())
            .filter_map(|id| self.source.template(id))
            .map(|template| {
                template
                    .bounding_box(BlockPos::new(0, 0, 0), Rotation::None)
                    .y_span()
            })
            .max()
            .unwrap_or(0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::pool::{PoolElementEntry, TemplatePool};
    use crate::template::PlacedTemplateBlock;
    use crate::rotation::Direction;
    use oxide_core::LegacyRandom;

    struct Pack {
        templates: HashMap<ResourceLocation, StructureTemplate>,
        pools: HashMap<ResourceLocation, TemplatePool>,
    }

    impl TemplateSource for Pack {
        fn template(&self, id: &ResourceLocation) -> Option<&StructureTemplate> {
            self.templates.get(id)
        }
        fn pool(&self, id: &ResourceLocation) -> Option<&TemplatePool> {
            self.pools.get(id)
        }
    }

    struct FlatGround(i32);
    impl SurfaceHeights for FlatGround {
        fn first_free_height(&self, _x: i32, _z: i32) -> i32 {
            self.0
        }
    }

    fn connector(
        pos: BlockPos,
        front: Direction,
        name: &str,
        target: &str,
        pool: &str,
    ) -> JigsawConnector {
        JigsawConnector {
            pos,
            front,
            top: Direction::Up,
            name: name.into(),
            target: target.into(),
            pool: ResourceLocation::minecraft(pool),
            final_state: BlockState::new(ResourceLocation::minecraft("air")),
            joint: JigsawJoint::Rollable,
            placement_priority: 0,
            selection_priority: 0,
        }
    }

    /// A 3x3x3 block of stone with connectors on the faces named in `sides`.
    fn room(sides: &[(Direction, &str, &str, &str)]) -> StructureTemplate {
        let mut blocks = Vec::new();
        for x in 0..3 {
            for y in 0..3 {
                for z in 0..3 {
                    blocks.push(PlacedTemplateBlock {
                        pos: BlockPos::new(x, y, z),
                        state: BlockState::new(ResourceLocation::minecraft("stone")),
                    });
                }
            }
        }
        let jigsaws = sides
            .iter()
            .map(|(front, name, target, pool)| {
                let pos = match front {
                    Direction::East => BlockPos::new(2, 1, 1),
                    Direction::West => BlockPos::new(0, 1, 1),
                    Direction::South => BlockPos::new(1, 1, 2),
                    _ => BlockPos::new(1, 1, 0),
                };
                connector(pos, *front, name, target, pool)
            })
            .collect();
        StructureTemplate {
            size: [3, 3, 3],
            blocks,
            jigsaws,
        }
    }

    fn pack() -> Pack {
        let mut templates = HashMap::new();
        // The start piece offers one connector east, wanting something named "side".
        templates.insert(
            ResourceLocation::minecraft("start"),
            room(&[(Direction::East, "start_exit", "side", "wing")]),
        );
        // The wing accepts from the west and offers another east, so the chain can continue.
        templates.insert(
            ResourceLocation::minecraft("wing"),
            room(&[
                (Direction::West, "side", "nothing", "empty"),
                (Direction::East, "side_exit", "side", "wing"),
            ]),
        );
        // A piece whose connector is named something the start never asks for. Facing is not
        // enough to make a piece unattachable -- all four rotations are tried, so any single
        // connector can be turned to face the right way. The *name* is what rules it out.
        templates.insert(
            ResourceLocation::minecraft("unattachable"),
            room(&[(Direction::East, "wrong_name", "nothing", "empty")]),
        );

        let mut pools = HashMap::new();
        pools.insert(
            ResourceLocation::minecraft("start"),
            TemplatePool {
                fallback: None,
                elements: vec![PoolElementEntry {
                    weight: 1,
                    element: PoolElement::Single {
                        location: ResourceLocation::minecraft("start"),
                        projection: Projection::Rigid,
                        processors: serde_json::Value::Null,
                    },
                }],
            },
        );
        pools.insert(
            ResourceLocation::minecraft("wing"),
            TemplatePool {
                fallback: None,
                elements: vec![PoolElementEntry {
                    weight: 1,
                    element: PoolElement::Single {
                        location: ResourceLocation::minecraft("wing"),
                        projection: Projection::Rigid,
                        processors: serde_json::Value::Null,
                    },
                }],
            },
        );
        pools.insert(
            ResourceLocation::minecraft("empty"),
            TemplatePool {
                fallback: None,
                elements: vec![],
            },
        );
        Pack { templates, pools }
    }

    fn settings(max_depth: i32) -> JigsawSettings {
        JigsawSettings {
            max_depth,
            max_distance_horizontal: 80,
            max_distance_vertical: 40,
            do_expansion_hack: false,
            project_start_to_heightmap: false,
            min_y: -64,
            max_y: 319,
        }
    }

    fn assemble(max_depth: i32, seed: i64) -> AssembledStructure {
        let mut random = LegacyRandom::new(seed);
        assemble_jigsaw(
            &ResourceLocation::minecraft("start"),
            BlockPos::new(0, 64, 0),
            &settings(max_depth),
            &mut random,
            &pack(),
            &FlatGround(64),
        )
        .expect("start pool resolves")
    }

    #[test]
    fn a_chain_of_rooms_grows_to_the_depth_limit() {
        let one = assemble(1, 1234);
        assert_eq!(one.pieces.len(), 2, "start plus one wing");
        let three = assemble(3, 1234);
        assert_eq!(three.pieces.len(), 4, "start plus three wings");
    }

    /// The failure the old stub had: children placed at the parent's connector rather than
    /// offset by their own, so every piece landed inside the last one.
    #[test]
    fn a_child_attaches_beside_its_parent_not_inside_it() {
        let structure = assemble(1, 1234);
        let [start, wing] = &structure.pieces[..] else {
            panic!("expected two pieces");
        };
        assert!(
            !start.bbox.intersects(&wing.bbox),
            "pieces overlap: {:?} and {:?}",
            start.bbox,
            wing.bbox
        );
        // Which way the pair runs depends on the start's rotation, so this asserts the property
        // that holds under all four: the boxes share a face. Grow one by a block and they meet.
        let grown = BoundingBox::new(
            start.bbox.min_x - 1,
            start.bbox.min_y,
            start.bbox.min_z - 1,
            start.bbox.max_x + 1,
            start.bbox.max_y,
            start.bbox.max_z + 1,
        );
        assert!(
            grown.intersects(&wing.bbox),
            "child is detached from its parent: {:?} and {:?}",
            start.bbox,
            wing.bbox
        );
        assert_eq!(wing.bbox.min_y, start.bbox.min_y, "same floor level");
    }

    #[test]
    fn a_connector_whose_target_does_not_match_places_nothing() {
        let mut pack = pack();
        // Point the start at a pool whose only piece has no matching connector name.
        pack.pools.insert(
            ResourceLocation::minecraft("wing"),
            TemplatePool {
                fallback: None,
                elements: vec![PoolElementEntry {
                    weight: 1,
                    element: PoolElement::Single {
                        location: ResourceLocation::minecraft("unattachable"),
                        projection: Projection::Rigid,
                        processors: serde_json::Value::Null,
                    },
                }],
            },
        );
        let mut random = LegacyRandom::new(1234);
        let structure = assemble_jigsaw(
            &ResourceLocation::minecraft("start"),
            BlockPos::new(0, 64, 0),
            &settings(4),
            &mut random,
            &pack,
            &FlatGround(64),
        )
        .unwrap();
        assert_eq!(
            structure.pieces.len(),
            1,
            "a piece that cannot attach must not be forced in"
        );
    }

    #[test]
    fn assembly_is_deterministic_for_one_seed() {
        let a = assemble(4, 99);
        let b = assemble(4, 99);
        assert_eq!(a.pieces.len(), b.pieces.len());
        for (left, right) in a.pieces.iter().zip(&b.pieces) {
            assert_eq!(left.origin, right.origin);
            assert_eq!(left.rotation, right.rotation);
            assert_eq!(left.bbox, right.bbox);
        }
    }

    #[test]
    fn different_seeds_rotate_the_start_differently() {
        // Spread the seeds out: java.util.Random's first `nextInt(4)` barely moves across
        // consecutive small seeds, so 0..40 is not a test of anything.
        let rotations: std::collections::HashSet<_> = (0..40)
            .map(|i| assemble(1, i * 7_777_777 + 13).pieces[0].rotation)
            .collect();
        assert!(
            rotations.len() > 1,
            "the start rotation must depend on the seed"
        );
    }

    #[test]
    fn pieces_stay_inside_the_distance_limit() {
        let mut tight = settings(20);
        tight.max_distance_horizontal = 10;
        let mut random = LegacyRandom::new(5);
        let structure = assemble_jigsaw(
            &ResourceLocation::minecraft("start"),
            BlockPos::new(0, 64, 0),
            &tight,
            &mut random,
            &pack(),
            &FlatGround(64),
        )
        .unwrap();
        // The limit is centred on the start piece's own box, not on the requested position.
        let start = structure.pieces[0].bbox;
        let center_x = (start.max_x + start.min_x) / 2;
        for piece in &structure.pieces[1..] {
            assert!(
                piece.bbox.min_x >= center_x - 10 && piece.bbox.max_x <= center_x + 10,
                "piece escaped the limit: {:?}",
                piece.bbox
            );
        }
    }

    #[test]
    fn a_free_region_rejects_overlap_but_allows_touching() {
        let mut free = FreeRegion::new(BoundingBox::new(0, 0, 0, 100, 100, 100));
        free.take(BoundingBox::new(0, 0, 0, 4, 4, 4));
        assert!(
            free.accepts(&BoundingBox::new(5, 0, 0, 9, 4, 4)),
            "boxes sharing a face must both fit"
        );
        assert!(
            !free.accepts(&BoundingBox::new(4, 0, 0, 8, 4, 4)),
            "one block of overlap must be rejected"
        );
        assert!(
            !free.accepts(&BoundingBox::new(96, 0, 0, 104, 4, 4)),
            "a box leaving the limit must be rejected"
        );
    }

    #[test]
    fn the_priority_queue_serves_highest_priority_first_then_fifo() {
        let mut queue = PriorityQueue::default();
        queue.add("low", 0);
        queue.add("high first", 5);
        queue.add("high second", 5);
        assert_eq!(queue.next(), Some("high first"));
        assert_eq!(queue.next(), Some("high second"));
        assert_eq!(queue.next(), Some("low"));
        assert_eq!(queue.next(), None);
    }
}
