package dev.oxide.plugin.provenance;

import org.bukkit.Chunk;
import org.bukkit.NamespacedKey;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.world.ChunkLoadEvent;
import org.bukkit.persistence.PersistentDataType;
import org.bukkit.plugin.Plugin;

import java.util.Map;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Records which chunks this server actually generated with Oxide, and answers that question
 * later for any loaded chunk.
 *
 * <p>This exists because the sidecar-based {@link ProvenanceLookup} cannot answer it: sidecars
 * are written by the offline {@code oxide-pregen} tool, never by a running server, so on a live
 * server that lookup reports {@code java} for every chunk including ones Rust just generated --
 * confidently wrong, which is worse than useless for a diagnostic.
 *
 * <p>How it works: {@code OxideChunkGenerator} calls {@link #record} for each chunk it
 * generates. The chunk is not available as a Bukkit {@link Chunk} at that point, so the mark is
 * held until the chunk loads and then written into its
 * {@link org.bukkit.persistence.PersistentDataContainer}, which is saved with the chunk. That
 * makes the answer survive restarts: a chunk generated by Oxide last week still says so.
 *
 * <p>A chunk with no mark reads as {@code JAVA}. That is accurate for a world this plugin has
 * generated into -- the fallback path, and any chunk predating the plugin, is vanilla-generated
 * by definition.
 */
public final class LiveProvenance implements Listener {

    /**
     * Guard against unbounded growth if chunks are generated but never loaded. Generation
     * outruns loading only transiently, so this is a leak stop, not an expected limit.
     */
    private static final int MAX_PENDING_PER_WORLD = 4096;

    private final NamespacedKey key;
    private final Map<UUID, Set<Long>> pendingByWorld = new ConcurrentHashMap<>();

    public LiveProvenance(Plugin plugin) {
        this.key = new NamespacedKey(plugin, "generated");
    }

    /** Called from the generator, on whatever thread generated the chunk. */
    public void record(UUID worldId, int chunkX, int chunkZ) {
        Set<Long> pending =
                pendingByWorld.computeIfAbsent(worldId, id -> ConcurrentHashMap.newKeySet());
        if (pending.size() < MAX_PENDING_PER_WORLD) {
            pending.add(chunkKey(chunkX, chunkZ));
        }
    }

    /**
     * Stamps the mark as the chunk loads. Folia dispatches this on the region thread owning the
     * chunk, which is the thread allowed to touch its persistent data.
     */
    @EventHandler
    public void onChunkLoad(ChunkLoadEvent event) {
        Set<Long> pending = pendingByWorld.get(event.getWorld().getUID());
        if (pending == null) {
            return;
        }
        Chunk chunk = event.getChunk();
        if (pending.remove(chunkKey(chunk.getX(), chunk.getZ()))) {
            chunk.getPersistentDataContainer().set(key, PersistentDataType.BYTE, (byte) 1);
        }
    }

    /** Whether this chunk was generated by Oxide. */
    public ChunkProvenance of(Chunk chunk) {
        return chunk.getPersistentDataContainer().has(key, PersistentDataType.BYTE)
                ? ChunkProvenance.OXIDE
                : ChunkProvenance.JAVA;
    }

    private static long chunkKey(int chunkX, int chunkZ) {
        return ((long) chunkX << 32) ^ (chunkZ & 0xFFFFFFFFL);
    }
}
