package dev.oxide.plugin.provenance;

import dev.oxide.plugin.generator.OxideChunkGenerator;
import org.bukkit.Chunk;
import org.bukkit.NamespacedKey;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.world.ChunkLoadEvent;
import org.bukkit.persistence.PersistentDataType;
import org.bukkit.plugin.Plugin;

import java.util.Map;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Records which chunks this server actually generated with Oxide, and answers that question
 * later for any loaded chunk.
 */
public final class LiveProvenance implements Listener {

    private static final int MAX_PENDING_PER_WORLD = 65536;

    private final NamespacedKey key;
    private final Map<UUID, Set<Long>> pendingByWorld = new ConcurrentHashMap<>();
    private final Set<Long> generatedChunks = ConcurrentHashMap.newKeySet();

    public LiveProvenance(Plugin plugin) {
        this.key = new NamespacedKey(plugin, "generated");
    }

    /** Called from the generator, on whatever thread generated the chunk. */
    public void record(UUID worldId, int chunkX, int chunkZ) {
        long packed = chunkKey(chunkX, chunkZ);
        generatedChunks.add(packed);
        Set<Long> pending =
                pendingByWorld.computeIfAbsent(worldId, id -> ConcurrentHashMap.newKeySet());
        if (pending.size() < MAX_PENDING_PER_WORLD) {
            pending.add(packed);
        }
    }

    /**
     * Stamps the mark as the chunk loads. Folia dispatches this on the region thread owning the
     * chunk, which is the thread allowed to touch its persistent data.
     */
    @EventHandler
    public void onChunkLoad(ChunkLoadEvent event) {
        Chunk chunk = event.getChunk();
        long packed = chunkKey(chunk.getX(), chunk.getZ());
        Set<Long> pending = pendingByWorld.get(event.getWorld().getUID());
        if (pending != null) {
            pending.remove(packed);
        }
        if (generatedChunks.contains(packed)) {
            chunk.getPersistentDataContainer().set(key, PersistentDataType.BYTE, (byte) 1);
        }
    }

    /** Whether this chunk was generated by Oxide. */
    public ChunkProvenance of(Chunk chunk) {
        if (chunk.getPersistentDataContainer().has(key, PersistentDataType.BYTE)) {
            return ChunkProvenance.OXIDE;
        }
        long packed = chunkKey(chunk.getX(), chunk.getZ());
        if (generatedChunks.contains(packed)) {
            return ChunkProvenance.OXIDE;
        }
        if (chunk.getWorld().getGenerator() instanceof OxideChunkGenerator) {
            return ChunkProvenance.OXIDE;
        }
        return ChunkProvenance.JAVA;
    }

    private static long chunkKey(int chunkX, int chunkZ) {
        return ((long) chunkX << 32) ^ (chunkZ & 0xFFFFFFFFL);
    }
}
