package dev.oxide.plugin.vertex;

import dev.oxide.plugin.ffi.OxideNative;
import dev.oxide.plugin.generator.GeneratorService;
import dev.vertex.engine.api.ChunkGenerationHook;
import dev.vertex.engine.api.ChunkRequest;
import dev.vertex.engine.api.ChunkTarget;
import dev.vertex.engine.api.HookResult;

import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.ValueLayout;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;

/**
 * Oxide's terrain generation, driven by the Vertex Engine instead of by Bukkit.
 *
 * <p>The engine path exists because the Bukkit one cannot express what Oxide already computes:
 * a {@code ChunkGenerator} has no way to write the biome grid, so the plugin throws away the
 * biome array the Rust side hands back and answers biomes again, per position, through a
 * {@code BiomeProvider}. Here both arrays land in the chunk from one generation call.
 *
 * <p>Every failure returns {@code FALLBACK} rather than throwing: a chunk generated by vanilla
 * is wrong-looking, a worldgen thread killed mid-chunk takes the region with it.
 */
final class OxideChunkHook implements ChunkGenerationHook {

    private final GeneratorService service;
    private final System.Logger logger;

    /**
     * Dimension+seed -> the open generator. Opening parses the datapack and builds the noise
     * router, so it happens once; {@link GeneratorService} already dedupes, this map only
     * avoids taking its lock on every chunk.
     */
    private final Map<String, OxideNative.Handle> handles = new ConcurrentHashMap<>();
    private final AtomicLong failures = new AtomicLong();

    OxideChunkHook(GeneratorService service, System.Logger logger) {
        this.service = service;
        this.logger = logger;
    }

    @Override
    public HookResult generate(ChunkRequest request, ChunkTarget target) {
        OxideNative.Handle handle;
        try {
            handle = handleFor(request);
        } catch (RuntimeException e) {
            report("could not open the oxide generator for " + request.dimensionId()
                    + " seed " + request.seed(), e);
            return HookResult.fallback(HookResult.FallbackReason.MODULE_ERROR);
        }

        // A dimension whose height the engine reports differently from what the datapack says
        // would silently write terrain at the wrong Y. Refuse it instead.
        if (handle.minY() != target.minY() || handle.height() != target.height()) {
            report("dimension shape mismatch for " + request.dimensionId()
                    + ": generator is " + handle.height() + " blocks from y=" + handle.minY()
                    + ", the level is " + target.height() + " from y=" + target.minY(), null);
            return HookResult.fallback(HookResult.FallbackReason.MODULE_ERROR);
        }

        int height = handle.height();
        int blockCount = 256 * height;
        int biomeCount = 64 * (height / 16);

        short[] blockIndices;
        short[] biomeIndices;
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment blocks = arena.allocate((long) blockCount * Short.BYTES);
            MemorySegment biomes = arena.allocate((long) biomeCount * Short.BYTES);
            try {
                handle.generateChunk(request.chunkX(), request.chunkZ(), blocks, biomes);
            } catch (RuntimeException e) {
                report("generation failed for chunk " + request.chunkX() + ", " + request.chunkZ(), e);
                return HookResult.fallback(HookResult.FallbackReason.MODULE_ERROR);
            }
            blockIndices = blocks.toArray(ValueLayout.JAVA_SHORT);
            biomeIndices = biomes.toArray(ValueLayout.JAVA_SHORT);
        }

        // Read the palettes after generating, not before: the Rust side interns block states as
        // it meets them, so a palette snapshot taken first can be short of what the indices
        // above refer to.
        target.setBlocks(blockPalette(handle), blockIndices);
        target.setBiomes(biomePalette(handle), biomeIndices);
        return HookResult.success();
    }

    private OxideNative.Handle handleFor(ChunkRequest request) {
        String key = request.dimensionId() + "@" + request.seed();
        return handles.computeIfAbsent(key, ignored -> {
            logger.log(System.Logger.Level.INFO, "opening the oxide generator for "
                    + request.dimensionId() + " with seed " + request.seed()
                    + " (parsing datapack, building noise router)");
            return service.openHandle(request.seed(), request.dimensionId());
        });
    }

    private static String[] blockPalette(OxideNative.Handle handle) {
        String[] palette = new String[handle.blockPaletteSize()];
        for (int i = 0; i < palette.length; i++) {
            palette[i] = handle.blockPaletteName(i);
        }
        return palette;
    }

    private static String[] biomePalette(OxideNative.Handle handle) {
        String[] palette = new String[handle.biomePaletteSize()];
        for (int i = 0; i < palette.length; i++) {
            palette[i] = handle.biomePaletteName(i);
        }
        return palette;
    }

    /**
     * First failure in full, then every hundredth. A failure here is usually systemic -- a bad
     * datapack, a closed handle -- and would otherwise log at chunk-generation rate.
     */
    private void report(String message, Throwable cause) {
        long count = failures.incrementAndGet();
        if (count == 1 || count % 100 == 0) {
            logger.log(System.Logger.Level.ERROR,
                    message + " (failure #" + count + "); this chunk falls back to vanilla", cause);
        }
    }
}
