[package]
name = "oxide-pregen"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
oxide-core.workspace = true
oxide-anvil.workspace = true
clap.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
rayon.workspace = true
